# Generated by Django 3.0.8 on 2020-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='confirm_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
